services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev  # Utiliser le Dockerfile de développement
    ports:
      - "${APP_PORT:-5000}:5000"
      - "38275:38275"  # Mapper le port Hot Reload WebSocket
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=${DB_NAME};User=${DB_USER};Password=${DB_PASSWORD};
      - DOTNET_WATCH_REFRESH_PORT=38275  # Définir le port Hot Reload WebSocket
    volumes:
      - ./app:/app  # Monter le code source directement dans /app
      - ./docker:/docker
      - ./caddy:/caddy
      - data_protection_keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  caddy:
    image: caddy:2
    container_name: caddy_server
    restart: unless-stopped
    ports:
      - "${CADDY_HTTP_PORT:-80}:80"
      - "${CADDY_HTTPS_PORT:-443}:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network

volumes:
  mysql_data:
  caddy_data:
  caddy_config:
  data_protection_keys:

networks:
  app-network:
    driver: bridge